### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by CSouque** [cchauve/plASgraph2#3]
Hi!

I have a weird error with roughly half of my samples when I run plASgraph2:

`Traceback (most recent call last):
  File "/home/cs477/plASgraph2/src/plASgraph2_classify.py", line 149, in <module>
    main_gfa(**arg_dict)
  File "/home/cs477/plASgraph2/src/plASgraph2_classify.py", line 84, in main_gfa
    prediction_df = test_one('', graph_file, model, parameters, '.')
  File "/home/cs477/plASgraph2/src/plASgraph2_classify.py", line 91, in test_one
    G = create_graph.read_single_graph(file_prefix, graph_file, sample_id, parameters['minimum_contig_length'])
  File "/home/cs477/plASgraph2/src/create_graph.py", line 219, in read_single_graph
    read_graph(graph_file, None, sample_id, graph, minimum_contig_length)
  File "/home/cs477/plASgraph2/src/create_graph.py", line 124, in read_graph
    assert node_id not in graph
AssertionError`

Do you know what could be causing this and how to fix it? 

Happy to provide a failing and succeeding assembly graph if this helps. 

Best,

**Comment by cchauve** [comment]
I would welcome to have examples of assembly graphs.

**Comment by CSouque** [comment]
GCID-2726 worked but GCID-2587 failed
[Assembly_graphs.zip](https://github.com/cchauve/plASgraph2/files/15154031/Assembly_graphs.zip)

**Comment by CSouque** [comment]
Hi! 

I wanted to check if you had any inputs and if more examples would be useful. We are currently doing a plasmid tool benchmarking projects, and it would be great if I could have the full results for plasgraph2

Best,

**Comment by cchauve** [comment]
My apologies, I have not had time to deal with this.
cedric chauve

________________________________________

**Comment by tvinar** [comment]
Could you please provide an input on which it fails? I can look into that.

**Comment by CSouque** [comment]
Hi!
Thanks for coming back to me! I managed to fix it, and it seems some of my assemblies graphs had gotten corrupted while transferring them? (see picture and file attached). Getting back to the original assemblies graphs seems to have fixed it, so it seems the error was due to a faulty graph (still no idea how that did happen)
[DIV2357.gfa.zip](https://github.com/cchauve/plASgraph2/files/15366847/DIV2357.gfa.zip)
<img width="1292" alt="Untitled 31" src="https://github.com/cchauve/plASgraph2/assets/26557032/9135c9a1-691a-4b0f-9069-03cd37df699a">

**Comment by JPWestley** [comment]
Hello CSouque. 

I am interested in your plasmid tool benchmarking project. Would you be willing to share what tools you are looking at, and which appear to be performing best? I am currently trying to decide which tool(s) to use for a project myself. You can email me at jw1235@exeter.ac.uk if you would prefer that.

Many thanks in advance!
Joe

**Comment by tvinar** [comment]
I would be interested as well ;)
